"""Motion HAL protocol definitions."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class AcsHal(Protocol):
    def connect(self, ip: str, port: int) -> None: ...

    def connect_simulator(self) -> None: ...

    def disconnect(self) -> None: ...

    def enable_all(self) -> None: ...

    def disable_all(self) -> None: ...

    def stop_all(self) -> None: ...

    def move_to(self, axis: int, pos_mm: float) -> None: ...

    def get_positions(self) -> list[float]: ...


@runtime_checkable
class KimmHal(Protocol):
    def connect(self, ip: str, port: int) -> None: ...

    def disconnect(self) -> None: ...

    def move_to_z(self, um: float) -> None: ...

    def get_z(self) -> float: ...


@runtime_checkable
class PicoHal(Protocol):
    def connect(self, *args, **kwargs) -> None: ...

    def disconnect(self) -> None: ...

    # Axis index convention: 1-based motor number (1..4).
    def move_relative(self, axis: int, steps: int) -> None: ...

    # Axis index convention: 1-based motor number (1..4).
    def get_position(self, axis: int) -> int: ...
