"""Motion HAL protocol definitions."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class AcsHal(Protocol):
    def connect(self, ip: str, port: int) -> None: ...

    def connect_simulator(self) -> None: ...

    def disconnect(self) -> None: ...

    def enable_all(self) -> None: ...

    def disable_all(self) -> None: ...

    def stop_all(self) -> None: ...

    def move_to(self, axis: int, pos_mm: float) -> None: ...

    def get_positions(self) -> list[float]: ...
    
    def is_moving(self) -> bool: ...

    def wait_in_position_all(self, timeout_ms: int = 30000) -> None: ...

    def wait_for_enabled_all(self, timeout_ms: int = 2000) -> bool: ...

    def is_enabled_all(self) -> bool: ...

    def move_atomic(self, targets: list[float]) -> None: ...


@runtime_checkable
class KimmHal(Protocol):
    def connect(self, ip: str, port: int) -> None: ...

    def disconnect(self) -> None: ...

    def move_to_z(self, um: float) -> None: ...

    def get_z(self) -> float: ...

    def servo_on(self) -> None: ...

    def servo_off(self) -> None: ...


@runtime_checkable
class PicoHal(Protocol):
    def connect(self, *args, **kwargs) -> None: ...

    def disconnect(self) -> None: ...

    # Axis index convention: 1-based motor number (1..4).
    def move_relative(self, axis: int, steps: int) -> None: ...

    # Axis index convention: 1-based motor number (1..4).
    def get_position(self, axis: int) -> int: ...

    def get_all_positions(self) -> list[int]: ...

    def zero(self, axis: int) -> None: ...

    def stop_all(self) -> None: ...

    def wait_motion_done(self, axis: int, timeout_ms: int) -> None: ...
